### ISSUE TITLE
loss function

### ISSUE THREAD

**Issue by youngzw** [TsingZ0/SHAN#1]
请问您实现的这篇文章的loss function是用的point-wise的方法吗（看了代码感觉是point-wise的思路，不过我对这个不是很确定=_=，所以向您请教下）？我看原论文里面用的是pair-wise的方法，尝试推导了您代码中写的正样本负样本损失之和好像不等于这个pairwise的损失
![image](https://user-images.githubusercontent.com/37242403/95745585-eed69e80-0cc7-11eb-8bda-54a9b16a985a.png)

**Comment by TsingZ0** [comment]
是的，我之前的版本用的是交叉熵损失，实验结果与pair-wise的差不多；最新修改的用了带pair-wise的损失函数。
